#pragma once

#include <string>

namespace booster {
namespace robot {

/**
 * @file const.hpp
 * @brief DDS topic names and identifiers shared by AI and LUI applications.
 *
 * These constants identify the subtitle and standalone ASR result streams
 * published by the robot services.
 *
 * @par Model support
 * @note Supported model: K1 | T1 | T2
 * @note Data is published only while the relevant AI or LUI service is
 * deployed, running, and producing results.
 */

/**
 * @brief DDS channel carrying conversational AI subtitles.
 *
 * Messages use booster_interface::msg::Subtitle and include recognized human
 * speech and robot-generated text. Use kBoosterRobotUserId to distinguish robot
 * subtitle entries from human entries.
 *
 * @note Supported model: K1 | T1 | T2
 */
static const std::string kTopicAiSubtitle = "rt/ai_subtitle";

/**
 * @brief DDS channel carrying standalone LUI ASR result chunks.
 *
 * Messages use booster_interface::msg::AsrChunk and contain recognized text in
 * the message `text` field.
 *
 * @note Supported model: K1 | T1 | T2
 */
static const std::string kTopicLuiAsrChunk = "rt/lui_asr_chunk";

/**
 * @brief Fixed subtitle user identifier used for robot-generated speech.
 *
 * A booster_interface::msg::Subtitle whose `user_id` equals this value was
 * generated by the robot. Other identifiers represent human participants.
 */
static const std::string kBoosterRobotUserId = "BoosterRobot";

}
} // namespace booster::robot
